### ISSUE TITLE
MyCHATAI

### ISSUE THREAD

**Issue by RysiekAI** [jerryjee120/MyChatAI-ChatGPT-client#4]
Hi,

1) What is the value of the "temperature" parameter you have set? I'm asking because I found an application (I don't remember the name now) where I can set these parameters when entering the prompt, as mentioned in the OPEN AI API documentation. This is particularly important since the GPT-4 API does not have a "standard" value for this parameter, and it must be set programmatically for any application."?
If you have set the default value yourself, please write down what it is and let me know if I can smoothly change it like in other native available applications.

2) Unlimited mode is cost-effective, It will only select the most relevant messages as context. - What did you mean by writing that - could you please explain in more detail?

**Comment by jerryjee120** [comment]
1. temperature setting will be added in the next update.
2. It means it will send the new message with relevant history messages(by similarity search) to ChatGPT, ignore the irrelevant ones.

**Comment by RysiekAI** [comment]
What is the value of the "temperature" parameter you have set now?

**Comment by jerryjee120** [comment]
according to OpenAI's API reference,  the default value for temperature is 1.

**Comment by RysiekAI** [comment]
ok and: Top_p ?

ps. next update - when ;) ?

**Comment by jerryjee120** [comment]
ok, Top_p will  be supported as well in the next update. 
Maybe in 3-5 workdays.

**Comment by RysiekAI** [comment]
next update ?

**Comment by RysiekAI** [comment]
I have one more question: what is the set maximum value for the input and output tokens in your native application, taking into account the GPT-4 API? Have you considered adjusting these values like you've done with the "temperature" parameter, as shown in the image below?

![IMG_6579](https://github.com/jerryjee120/MyChatAI-ChatGPT-client/assets/133009242/04ec1ca7-0910-4c26-99bb-f0c35f5627a4)
